base_url: http://localhost:8147

code:
  valid_time: 86400

socket:
  addr: 0code-generator-socket

db:
  path: ./db/base.db
  table:
    name: codes
    columns:
      - name: user
        type: TEXT
      - name: code
        type: TEXT
      - name: generated
        type: INTEGER
      - name: valid_until
        type: INTEGER
      - name: already_used
        type: INTEGER
